name: Set up Arch Linux
description: Install deps needed on Arch

runs:
  using: composite
  steps:
    - name: Get week
      id: date
      shell: bash
      run: echo "week=$(date +%Y-%U)" >> $GITHUB_OUTPUT

    - name: Restore package cache
      uses: actions/cache/restore@v5
      with:
        path: |
          /var/cache/pacman/pkg
          /home/builder/.cache/yay
        key: pacman-${{ steps.date.outputs.week }}-${{ hashFiles('.github/actions/setup-arch/action.yml') }}
        restore-keys: |
          pacman-${{ steps.date.outputs.week }}-
          pacman-

    - name: Install deps
      shell: bash
      run: |
        pacman -Syu --needed --noconfirm sudo base-devel cmake ninja fish git clang qt6-declarative python

    - name: Install yay
      shell: bash
      run: |
        useradd -m builder
        echo 'builder ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
        chown -R builder:builder /home/builder

        sudo -u builder git clone https://aur.archlinux.org/yay-bin.git /home/builder/yay-bin
        cd /home/builder/yay-bin
        sudo -u builder makepkg -si --noconfirm

    - name: Install quickshell-git
      shell: bash
      run: sudo -u builder yay -S --noconfirm quickshell-git

    - name: Save packages to cache
      uses: actions/cache/save@v5
      with:
        path: |
          /var/cache/pacman/pkg
          /home/builder/.cache/yay
        key: pacman-${{ steps.date.outputs.week }}-${{ hashFiles('.github/actions/setup-arch/action.yml') }}
